### ISSUE TITLE
Error output written in mysql_log from mysql_tquery/mysql_pquery is corrupted

### ISSUE THREAD

**Issue by Konstantinos-Sk** [pBlueG/SA-MP-MySQL#120]
Version R41.

I was testing if some certain errors are given in OnQueryError and just noticed that:
```
[ERROR] €¬q
[ERROR] ÈÏ/ 
[ERROR] Ä 
[ERROR] ¸¶/ 
```
I executed the same faulty query and each time random characters are given.

**Comment by Konstantinos-Sk** [comment]
Another one I just found: using _cache_num_rows()_ to a place without active cache reports line 182 from a_mysql.inc file which actually makes sense since the function is in the include. Instead of calling cache_get_row_count or moving the function to the script, is there any other way to report the previous place was called from for that specific function?

**Comment by maddinat0r** [comment]
Which query were you executing? 
And I'm already aware of that problem with calling natives in non-public functions. I'm working on a way to incorporate a small AMX call trace into log calls.

**Comment by Konstantinos-Sk** [comment]
So far, any query with error in the syntax or table/column that does not exist gives that output.

**Comment by Konstantinos-Sk** [comment]
I run samp-server.exe many times because of testing and I mostly click on X button instead of typing exit. I get the message that "SA-MP dedicated server has stopped working". I downgrade to R40 and this doesn't happen. Updated to R41 again to make sure and it happens.

**Comment by Konstantinos-Sk** [comment]
It's getting even more weird. Since today morning, when a fault query (table does not exist) is executed, samp-server.exe stops working immediately. I don't know if the debug output from Visual Studio is at all useful: http://pastebin.com/raw/Vb8vbQyb

**Comment by maddinat0r** [comment]
I can't seem to reproduce the error message bug with a query like `SEuLECT 1234` or `SELECT * FROM invalidtable`.
I also can't reproduce the "server stopped working" issue. The log core reacts when you press the X button and shuts down itself correctly, but this is already implemented in R40. [There are no notable changes between the log-core used in R40 and the one in R41.](https://github.com/maddinat0r/samp-log-core/compare/e2a335bac518fc435508765ec3a1fec5e4b4bd02...dc20a9a1498f25f90c3bcaa1845be9d58717324a) The worst thing you should experience is a "freeze" when pressing the X button. That means the log core is writing all remaining logs into their log files in background.
And that error code you receive on crash stands for `INVALID_CRUNTIME_PARAMETER`, and I'm not really sure if this is caused by the MySQL plugin nor the log core.
If you're running this through Visual Studio, you could compile everything in Debug configuration and launch your SA:MP server through the Visual Studio debugger. This way you should get more descriptive error messages.

**Comment by maddinat0r** [comment]
Can you also tell me more about your setup (system, used plugins, used includes, ...)?

**Comment by Konstantinos-Sk** [comment]
I'm not sure if I can manage to link them all together and compile the plugin myself.

In the AppVeyor, the "Configuration: Debug" option does anything useful? Because if I run it, I get: http://i.imgur.com/S7UJrTY.png

**Comment by maddinat0r** [comment]
Yes, the AppVeyor debug build should work too. You can press "Retry" in that window and the debugger should open with a call trace somewhere. Take a look at that trace and you should see if that crash was really caused within the SA:MP server or an other plugin.

**Comment by Konstantinos-Sk** [comment]
The second box is given all the time when clicking "Retry" and no debugger opens. I tried the version for the commit above but the problem still persists.

**Comment by Konstantinos-Sk** [comment]
I finally found the reason causing all this. I was testing the specifiers in _logtimeformat_ (**server.cfg**) and I had apparently an invalid specifier. 

I also re-downloaded the last compiled version and it reports the errors again.

**Comment by maddinat0r** [comment]
Ah, I see. I should probably check if the datetime format string is valid first and then set it.
