### ISSUE TITLE
CentOS 7 Mysql R41 Issues

### ISSUE THREAD

**Issue by Abyss-z94** [pBlueG/SA-MP-MySQL#130]
My CentOS 7 VPS can't load mysql R41, the error is 

"Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)"

my server still have 'libmysqlclient.so.18' but i don't know why alway load failed

/usr/lib64/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient.so.18.1.0

Anyone know that trouble? Help me please !

**Comment by Abyss-z94** [comment]
my server still have 'libmysqlclient.so.18' but i don't know why alway load failed

/usr/lib64/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient.so.18
/usr/lib64/mysql/libmysqlclient.so.18.1.0

**Comment by Jeroen52** [comment]
Please read the FAQ, could be that you don't have the MySQL client properly installed: https://github.com/pBlueG/SA-MP-MySQL#faq

**Comment by Jeroen52** [comment]
Try `yum install mariadb-libs-5.5.44-2.el7.centos.i686` and after that `yum update` just to be sure.

**Comment by Abyss-z94** [comment]
i were do that early, but that not work tho.

[root@localhost GvC]# yum install mariadb-libs-5.5.44-2.el7.centos.i686
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.vonline.vn
 * extras: mirrors.vonline.vn
 * updates: mirrors.vonline.vn
Package 1:mariadb-libs-5.5.44-2.el7.centos.i686 is obsoleted by mysql-community-                                                                                                                                                             libs-5.6.33-2.el7.x86_64 which is already installed
Nothing to do
[root@localhost GvC]# yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.vonline.vn
 * extras: mirrors.vonline.vn
 * updates: mirrors.vonline.vn
No packages marked for update
[root@localhost GvC]#

**Comment by Jeroen52** [comment]
Odd, the `mysql-community-libs` package does not exist for me.

Try to install the following: `yum install mariadb-libs.i686`
After that, try to start the server again.

**Comment by Abyss-z94** [comment]
That still installed tho

[root@localhost ~] yum install mariadb-libs.i686
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.vonline.vn
 * extras: mirrors.vonline.vn
 * updates: mirrors.vonline.vn
Package 1:mariadb-libs-5.5.50-1.el7_2.i686 is obsoleted by mysql-community-libs-5.6.33-2.el7.x86_64 which is already installed
Nothing to do
[root@localhost ~]

I don't know what i gona do now. That Plugins were f*ck me up

**Comment by Jeroen52** [comment]
Can you check which repositories offer `mysql-community-libs` for you?
Check it with `yum info mysql-community-libs`

**Comment by Abyss-z94** [comment]
There is it

[root@localhost ~] yum info mysql-community-libs
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.vonline.vn
 * extras: mirrors.vonline.vn
 * updates: mirrors.vonline.vn
Installed Packages
Name        : mysql-community-libs
Arch        : x86_64
Version     : 5.6.33
Release     : 2.el7
Size        : 9.2 M
Repo        : installed
From repo   : mysql56-community
Summary     : Shared libraries for MySQL database client applications
URL         : http://www.mysql.com/
License     : Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights
            : reserved. Under GPLv2 license as shown in the Description field.
Description : This package contains the shared libraries for MySQL client
            : applications.

Available Packages
Name        : mysql-community-libs
Arch        : i686
Version     : 5.6.33
Release     : 2.el7
Size        : 2.0 M
Repo        : mysql56-community/x86_64
Summary     : Shared libraries for MySQL database client applications
URL         : http://www.mysql.com/
License     : Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights
            : reserved. Under GPLv2 license as shown in the Description field.
Description : This package contains the shared libraries for MySQL client
            : applications.

[root@localhost ~]

**Comment by Abyss-z94** [comment]
do you realize some problem here mate

**Comment by Jeroen52** [comment]
It appears that you are using the mysql56-community repo instead of the standard CentOS repositories that include MariaDB instead.

Try to do the following, it should install the i686 arch libs. `yum install mysql-community-libs.i686`

After that you should be able to start the SAMP server with the MySQL plugin, if there is still an error we probably need to make a symlink or two.


Here is some additional info about the transition from MySQL in CentOS 6 to MariaDB in CentOS 7: https://mariadb.com/blog/rhel7-transition-mysql-mariadb-first-look

**Comment by Abyss-z94** [comment]
That worked mate. Big thanks for you man. That problem were wasted my day just stay on the screen and wait someone like u sovle that thing ! <3

**Comment by Jeroen52** [comment]
@Abyss-z94 Poking around in RPM and Yum is fun after you've learned how it works, I have even started to make my own packages.

A little instruction how to resolve this issue:
1. Your error code is very similar to an error in the FAQ that states the following:
    >Q: I get a Failed (libmysqlclient_r.so.18: cannot open shared object file: No such file or directory) error, how do I fix this?
    >A: You don't have the MySQL client library installed. Install it through your package manager. Make sure you install the 32bit (i386, i686, etc) library, or else the plugin won't run.
2. With the knowledge that SAMP plugins require to be built on 32-bit machines, generally needs 32-bit deps and this specific error message that is similar means that I have to search for 32-bit libraries. Your original post indicates that you have only installed 64-bit libraries.
3. I did a `yum whatprovides libmysqlclient.so.18` and I got multiple answers from that. Pick the one that has been built for a 32-bit architecture (i686), in your example that would be `mysql-community-libs`, so the 32-bit package would be `mysql-community-libs.i686`
4. Yum install it, simply use: `yum install mysql-community-libs.i686`

Since this has been resolved, I think that you can close this issue.

**Comment by Abyss-z94** [comment]
Ya that right ! Thanks you man.
