### ISSUE TITLE
Invalid connection handle error after succesful connection

### ISSUE THREAD

**Issue by mikroware** [pBlueG/SA-MP-MySQL#170]
I am using the latest plugin version for a server. It is build up from different filterscripts, each with its own task. As OnGameModeInit loads after OnFilterScriptInit, the first filterscript will configure the database. The connection message also comes before the other filterscripts load. The other filterscripts will use OnFilterScriptInit to load some initialization data from the database. It seems the data is loading correctly. So far so good. 

However in the mysql logs it still prints a lot of the following errors:

```
[ERROR] mysql_tquery: invalid connection handle '1'
```

This only happens when the server is started. It does not happen when the filterscript is reloaded. Is there any specific reason for this? Is there a way to avoid having those errors?

**Comment by maddinat0r** [comment]
Can you enable full logging `mysql_log(ALL);`, reproduce your issue and upload the log file here?

**Comment by mikroware** [comment]
When I add `mysql_log(ALL);` just before the connect, the `invalid connection handle` errors are gone. When I remove that line again, the errors are back.

Still want a part of the log file? Because does not look like there is anything useful in it considering the above mentioned situation.

**Comment by mikroware** [comment]
Woops, I made a terrible mistake. Apparently the logs are from `OnFilterScriptExit`. So I guess my question would be, where to place `mysql_close(db);` or is it not even necessary when the server is being shut down?

**Comment by maddinat0r** [comment]
Theoretically the plugin should close all remaining connections on server shutdown. However, it won't do so on a gamemode restart (gmx). That's why you always should close connections if you don't need them.

You could implement a global reference counter (through the GVar plugin for example), where you increase the counter on `OnFilterScriptInit` and `OnGameModeInit` and decrease it on `OnFilterScriptExit` and `OnGameModeExit`. If the counter is zero before increasing it in `OnScriptInit`, you create the connection. If the counter is zero after decreasing it in `OnScriptExit`, you close the connection.

**Comment by mikroware** [comment]
Thanks for the idea! I have implemented it by indeed using the GVar plugin and making use of ALS hooking in a common include.
