### ISSUE TITLE
Discord or something 

### ISSUE THREAD

**Issue by samp-pinch** [pBlueG/SA-MP-MySQL#221]
Is there a discord for this plugin?
Where anyone can get assistance, please do not send Southclaws's where you get ban for saying "I bypassed Kalcor's whois guard"

Or is there anyone willing to give me his discord name so I can ask few questions...?

thank you, sorry for being selfish I suppose you all are busy...

**Comment by AmyrAhmady** [comment]
Your first ban was because you were advertising a ddos/booter/stresser website.
You clearly put that webste URL in your discord username and kept saying to change my nickname on samp discord instead; And you know that doesnt help cause people can still see your advertisement. advertising a website is allowed but not any. What you were doing was completely illegal in any way, its not related to samp discord and its rules.

Your second ban was because you were ban evading, you joined with another account to ban evade and started acting just like before.

and FYI, your first account is unbanned, it got unbanned exactly the moment your second account got banned, to give you another chance

it’s your choice, all they want is you atleast respect international/internet rules, not just samp discord. Act like a normal human being.

Hope to see you there again with your main account.

**Comment by samp-pinch** [comment]
Yep, I got unbanned and banned for thing I said b4

**Comment by maddinat0r** [comment]
No, there’s no Discord for this plugin and there won’t be one. If you have an urge to contact me, feel free to mail me. My github mail address is public.
