### ISSUE TITLE
ORM system BUG

### ISSUE THREAD

**Issue by zndn1997** [pBlueG/SA-MP-MySQL#66]
if I use orm_destroy during orm_update or orm_insert query execute, and this situation many calling, some users data destroyed or saved strange data.

Sorry my bad english.

This mean:
Ex)
1. A, B, C, D, E players are connected.
2. B, C, E players using 'save user data' command.
3. orm_update is not completely executed, But B, C, E players are disconnect server and orm_destroy is calling. (orm_update will executed after 100ms, but users disconnect after use command and 30ms.)
4. This situation make some user data wrong save.

**Comment by maddinat0r** [comment]
Your described situation is technically impossible, because there's only one thread the gamemode is executed in, thus the code will only continue execution when `orm_update` completely finishes. That means `orm_destroy` can't be called before/while `orm_update` finished/is executing.
Also destroying an ORM instance does not affect the query execution in any way.

If your queries really are malformed in any way, enable full logging and share the output here.

**Comment by zndn1997** [comment]
I fix this problem how change code ORM to cache migration.
