### ISSUE TITLE
VS C++ 2015

### ISSUE THREAD

**Issue by NegativeIQ** [pBlueG/SA-MP-MySQL#93]
Hey, guys, could you please compile plugin with anything other than VS C++ 2015 (Toolset v14)

Im on windows 7, and to install C++ 2015 i need SP1 that i just dont want to install for a several good reasons from my perspective.

I would be grateful as i tried to build it myself but im just not for these :D

**Comment by maddinat0r** [comment]
Sorry, but I won't recompile it with an older compiler (`vc130` in this case), since I'd have to  
 1. install VS2012/2013
 2. recompile Boost completely with vc120
 3. make sure the code doesn't use any C++ language features not available in `vc120`

That's just too troublesome for me.

And since R40 is depending on said C++ language features, I'll have to stay on `vc140` anyways.

So if you *really* want to use a different compiler version, you'd have to follow those three steps above.
